#!/usr/bin/env python3
from datetime import datetime

def main():
    x = input("Ingrese un numero: ")
    x = datetime.strptime(x, "%d")
    now = datetime.now() + x
    print(now.strftime("%A, %B %d, %Y"))


if __name__ == "__main__":
    main()
