name: Revisión de estilo con flake8

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar flake8
        run: |
          python -m pip install flake8

      - name: Ejecutar flake8 en tarea01
        run: |
          flake8 Tareas/tarea01/ejercicio01/main.py

