name: Ejecutar script Python al hacer PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar el script de la tarea
        run: |
          cd tareas/tarea01/ejercicio01
          python3 main.py

